global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '${ALERTMANAGER_EMAIL}'
  smtp_auth_username: '${ALERTMANAGER_EMAIL}'
  smtp_auth_password: '${ALERTMANAGER_EMAIL_PASSWORD}'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: '${ALERTMANAGER_EMAIL}'
        send_resolved: true 