name: ps_ecommerce
services:
  mysql:
    container_name: mysql_db
    image: mysql:8.0
    user: "999:999"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-storage:/var/lib/mysql
    networks:
      - database_network

  prestashop:
    container_name: prestashop
    build: .
    user: "root:root" 
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PS_DEV_MODE: 0
      PS_INSTALL_AUTO: 1
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
      PS_COUNTRY: FR
      PS_LANGUAGE: fr
      PS_DOMAIN: localhost:8080
      DB_SERVER: mysql_db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWORD}
      ADMIN_MAIL: ${PS_ADMIN_EMAIL}
      ADMIN_PASSWD: ${PS_ADMIN_PASSWORD}
    networks:
      - prestashop_network
      - database_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    user: "www-data:www-data"
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql_db
    networks:
      - database_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    user: "65534:65534"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    networks:
      - monitoring_network

  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "472:472"
    ports:
      - "3001:3000"
    networks:
      - monitoring_network
    volumes: 
      - grafana-storage:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboard.json:/etc/grafana/provisioning/dashboards/system-monitoring.json

  cadvisor: 
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    platform: linux/arm64
    user: "root:root"
    ports: 
      - "8090:8080"
    networks:
      - monitoring_network
    volumes: 
      - cadvisor-storage:/var/lib/grafana
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    privileged: true

  node_exporter: 
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    user: "65534:65534"
    ports: 
      - "9100:9100"
    networks:
      - monitoring_network
    volumes: 
      - node-exporter-storage:/var/lib/grafana

  alertmanager: 
    container_name: alertmanager
    image: quay.io/prometheus/alertmanager
    user: "65534:65534"
    ports: 
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    environment:
      - ALERTMANAGER_EMAIL=${ALERTMANAGER_EMAIL}
      - ALERTMANAGER_EMAIL_PASSWORD=${ALERTMANAGER_EMAIL_PASSWORD}
    networks:
      - monitoring_network

networks:
    database_network:
    prestashop_network:
    monitoring_network:

volumes:
    mysql-storage:
    grafana-storage:
    cadvisor-storage:
    node-exporter-storage:
